export const hiddenBottomNavbar = [
    "/chat",
    "/edit-profile",
    "/feed",
    "/video-call",
    "/voice-call",
    "/login",
    "/password",
    "/otp",
    "/signup",
    "/username",
    "/name",
    "/createPost",
    "/post",
    "/comments",
  ];